- name: print certificate information
  debug:
    msg: |
      Certificate:       {{ letsencrypt_domain_names[0] }}
      Expires in days:   {{ letsencrypt_expiry_time_days }}
      Current domains:   {{ letsencrypt_certificate_domain_names }}
      Inventory domains: {{ letsencrypt_domain_names | sort | join(' ') }}
      Domains match:     {{ letsencrypt_certificate_names_match }}
      Update required:   {{ letsencrypt_renew }}
      {% if letsencrypt_force_renew == False and letsencrypt_renew == True %}

      "y" to generate
      Any other character to skip
      "CRTL + c - a" to abort
      {% elif letsencrypt_force_renew == True and letsencrypt_renew == True %}

      AUTOMATIC RENEWAL ENABLED (letsencrypt_force_renew is True)
      {% else %}

      NO ACTION REQUIRED
      {% endif %}

- pause:
    prompt: ""
  register: letsencrypt_renew_question_prompt
  when: >
    letsencrypt_force_renew == False and
    letsencrypt_renew == True


- name: inform about ending the host if letsencrypt_renew is not True
  debug:
    msg: "Ending the host as letsencrypt_renew is not True"
  when: letsencrypt_renew != True
- name: end the host if letsencrypt_renew is not True
  meta: end_host
  when: letsencrypt_renew != True


- name: enable generation of certificate
  set_fact:
    letsencrypt_generate: True
  when: >
    letsencrypt_renew == True and letsencrypt_force_renew == True or
    letsencrypt_renew == True and letsencrypt_renew_question_prompt.get('user_input', False) == "y"
