- name: "{{ letsencrypt_domain_names[0] }} | status"
  debug:
    msg: |

      {% if letsencrypt_exists == False %}
      Certificate:       {{ letsencrypt_domain_names[0] }}
      Exists:            {{ letsencrypt_exists }}

      DECISION REQUIRED

      {% elif letsencrypt_exists == True and letsencrypt_certificate_names_match == True and letsencrypt_time_to_renew == False %}
      Certificate:       {{ letsencrypt_domain_names[0] }}
      Exists:            {{ letsencrypt_exists }}
      Time to renew:     {{ letsencrypt_time_to_renew }}
      Expires in days:   {{ letsencrypt_expiry_time_days }}
      Domains match:     {{ letsencrypt_certificate_names_match }}

      NOTHING TO DO

      {% elif letsencrypt_exists == True and letsencrypt_certificate_names_match == True and letsencrypt_time_to_renew == True %}
      Certificate:       {{ letsencrypt_domain_names[0] }}
      Exists:            {{ letsencrypt_exists }}
      Time to renew:     {{ letsencrypt_time_to_renew }}
      Expires in days:   {{ letsencrypt_expiry_time_days }}
      Domains match:     {{ letsencrypt_certificate_names_match }}

      AUTOMATIC RENEWAL ENABLED

      {% elif letsencrypt_exists == True and letsencrypt_certificate_names_match == False %}
      Certificate:       {{ letsencrypt_domain_names[0] }}
      Exists:            {{ letsencrypt_exists }}
      Time to renew:     {{ letsencrypt_time_to_renew }}
      Expires in days:   {{ letsencrypt_expiry_time_days }}
      Domains match:     {{ letsencrypt_certificate_names_match }}

      Old domains:       {{ letsencrypt_certificate_domain_names }}
      New domains:       {{ letsencrypt_domain_names | sort | join(' ') }}

      DECISION REQUIRED

      {% endif %}
      {% if letsencrypt_exists == False or letsencrypt_certificate_names_match == False %}
      "y" to generate
      Any other character to skip
      "CRTL + c - a" to abort
      {% endif %}

- pause:
    prompt: ""
  register: letsencrypt_renew_question_prompt
  when: letsencrypt_exists == False or letsencrypt_certificate_names_match == False



- name: "{{ letsencrypt_domain_names[0] }} | END HOST - NOT TAKING ACTION"
  debug:
    msg: "END HOST - NOT TAKING ACTION"
  when: >
    letsencrypt_exists == False and letsencrypt_renew_question_prompt.get('user_input', False) != "y" or
    letsencrypt_certificate_names_match == False and letsencrypt_renew_question_prompt.get('user_input', False) != "y" or
    letsencrypt_exists == True and letsencrypt_certificate_names_match == True and letsencrypt_time_to_renew == False
- meta: end_host
  when: >
    letsencrypt_exists == False and letsencrypt_renew_question_prompt.get('user_input', False) != "y" or
    letsencrypt_certificate_names_match == False and letsencrypt_renew_question_prompt.get('user_input', False) != "y" or
    letsencrypt_exists == True and letsencrypt_certificate_names_match == True and letsencrypt_time_to_renew == False



- name: "{{ letsencrypt_domain_names[0] }} | set letsencrypt_generate True"
  set_fact:
    letsencrypt_generate: True
  when: >
    letsencrypt_exists == True and letsencrypt_certificate_names_match == True and letsencrypt_time_to_renew == True or
    letsencrypt_renew_question_prompt.get('user_input', False) == "y"
