- name: "check presence"
  stat:
    path: "/etc/letsencrypt/live/{{ letsencrypt_domain_names[0] }}/fullchain.pem"
  register: letsencrypt_stat

- name: "set letsencrypt_exists True"
  set_fact:
    letsencrypt_exists: True
  when: letsencrypt_stat.stat.exists == True



- name: "get expiry date of existing certificate"
  shell: |
    date --date="$(openssl x509 -in /etc/letsencrypt/live/{{ letsencrypt_domain_names[0] }}/fullchain.pem -noout -enddate | cut -d= -f 2)" +%s
  register: letsencrypt_expiry_date_check
  when: letsencrypt_exists == True

- name: "get domain names of existing certificate"
  shell: |
    openssl x509 -noout -text -nameopt multiline -in /etc/letsencrypt/live/{{ letsencrypt_domain_names[0] }}/fullchain.pem \
      | grep '    DNS:' \
      | sed -e 's/DNS:/ /g' -e 's/,//g' -e 's/  */ /g' -e 's/^[ \t]*//'
  register: letsencrypt_certificate_domain_names
  when: letsencrypt_exists == True

- name: "set facts"
  set_fact:
    letsencrypt_certificate_expiry_date_seconds: "{{ letsencrypt_expiry_date_check.stdout }}"
    letsencrypt_current_date_seconds: "{{ ansible_date_time['epoch'] }}"
    letsencrypt_certificate_domain_names: "{{ letsencrypt_certificate_domain_names.stdout }}"
  when: letsencrypt_exists == True

- name: "calculate time until expiry"
  set_fact:
    letsencrypt_expiry_time_days: "{{ ( (letsencrypt_certificate_expiry_date_seconds | int - letsencrypt_current_date_seconds | int ) / 86400 ) | round }}"
  when: letsencrypt_exists == True



- name: "set letsencrypt_certificate_names_match True"
  set_fact:
    letsencrypt_certificate_names_match: True
  when: letsencrypt_certificate_domain_names == letsencrypt_domain_names | sort | join(' ')

- name: "set letsencrypt_time_to_renew True"
  set_fact:
    letsencrypt_time_to_renew: True
  when: >
    letsencrypt_exists == True and
    letsencrypt_expiry_time_days | int <= letsencrypt_renew_days_max | int
