- name: execute post hook shell script
  shell: |
    set -x
    exec 2>&1
    {{ letsencrypt_post_hook }}
  args:
    executable: /bin/bash
  register: letsencrypt_post_hook_out
  when: letsencrypt_post_hook != False

- name: execute post hook shell script output
  debug:
    msg: |
      return code: {{ letsencrypt_post_hook_out_result.rc }}
      {{ letsencrypt_post_hook_out_result.stdout }}
  failed_when: letsencrypt_post_hook_out_result.failed == True
  with_items: "{{ letsencrypt_post_hook_out.results }}"
  loop_control:
    loop_var: letsencrypt_post_hook_out_result
  when: letsencrypt_post_hook != False
