- name: "{{ letsencrypt_domain_names[0] }} | run letsencrypt_post_hook"
  shell: |
    set -x
    exec 2>&1
    {{ letsencrypt_post_hook }}
  args:
    executable: /bin/bash
  register: letsencrypt_post_hook_out
  when: letsencrypt_post_hook != False

- name: "{{ letsencrypt_domain_names[0] }} | run letsencrypt_post_hook output"
  debug:
    msg: |
      return code: {{ letsencrypt_post_hook_out.rc }}
      {{ letsencrypt_post_hook_out.stdout }}
  failed_when: letsencrypt_post_hook_out.failed == True
  when: letsencrypt_post_hook != False
